// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/book.dart';
import 'api/coins.dart';
import 'api/cold.dart';
import 'api/core.dart';
import 'api/network.dart';
import 'api/nodes.dart';
import 'api/preferences.dart';
import 'api/price.dart';
import 'api/proof.dart';
import 'api/requests.dart';
import 'api/send.dart';
import 'api/sync.dart';
import 'api/wallets.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ColdRequestPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColdRequest;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ColdSendPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColdSend;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_FrameReaderPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameReader;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_OpenWalletPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenWallet;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_PreparedSendPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPreparedSend;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  ColdRequest
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColdRequest(
    dynamic raw,
  );

  @protected
  ColdSend
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColdSend(
    dynamic raw,
  );

  @protected
  FrameReader
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameReader(
    dynamic raw,
  );

  @protected
  OpenWallet
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenWallet(
    dynamic raw,
  );

  @protected
  PreparedSend
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPreparedSend(
    dynamic raw,
  );

  @protected
  ColdRequest
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColdRequest(
    dynamic raw,
  );

  @protected
  ColdSend
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColdSend(
    dynamic raw,
  );

  @protected
  FrameReader
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameReader(
    dynamic raw,
  );

  @protected
  OpenWallet
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenWallet(
    dynamic raw,
  );

  @protected
  PreparedSend
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPreparedSend(
    dynamic raw,
  );

  @protected
  ColdRequest
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColdRequest(
    dynamic raw,
  );

  @protected
  ColdSend
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColdSend(
    dynamic raw,
  );

  @protected
  FrameReader
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameReader(
    dynamic raw,
  );

  @protected
  OpenWallet
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenWallet(
    dynamic raw,
  );

  @protected
  PreparedSend
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPreparedSend(
    dynamic raw,
  );

  @protected
  RustStreamSink<SyncEvent> dco_decode_StreamSink_sync_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AddressKind dco_decode_address_kind(dynamic raw);

  @protected
  AddressRow dco_decode_address_row(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  Preferences dco_decode_box_autoadd_preferences(dynamic raw);

  @protected
  SyncFailure dco_decode_box_autoadd_sync_failure(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  CertificateDetails dco_decode_certificate_details(dynamic raw);

  @protected
  CoinRow dco_decode_coin_row(dynamic raw);

  @protected
  ColdFailure dco_decode_cold_failure(dynamic raw);

  @protected
  ColdImport dco_decode_cold_import(dynamic raw);

  @protected
  ColdKind dco_decode_cold_kind(dynamic raw);

  @protected
  ColdMessage dco_decode_cold_message(dynamic raw);

  @protected
  ColdRequestSummary dco_decode_cold_request_summary(dynamic raw);

  @protected
  ContactRow dco_decode_contact_row(dynamic raw);

  @protected
  CoreInfo dco_decode_core_info(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FeePriority dco_decode_fee_priority(dynamic raw);

  @protected
  HistoryItem dco_decode_history_item(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AddressRow> dco_decode_list_address_row(dynamic raw);

  @protected
  List<CoinRow> dco_decode_list_coin_row(dynamic raw);

  @protected
  List<ContactRow> dco_decode_list_contact_row(dynamic raw);

  @protected
  List<HistoryItem> dco_decode_list_history_item(dynamic raw);

  @protected
  List<LocalNode> dco_decode_list_local_node(dynamic raw);

  @protected
  List<Network> dco_decode_list_network(dynamic raw);

  @protected
  List<NodeChoice> dco_decode_list_node_choice(dynamic raw);

  @protected
  List<Payment> dco_decode_list_payment(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RequestRow> dco_decode_list_request_row(dynamic raw);

  @protected
  List<WalletSummary> dco_decode_list_wallet_summary(dynamic raw);

  @protected
  LocalNode dco_decode_local_node(dynamic raw);

  @protected
  LwsHealth dco_decode_lws_health(dynamic raw);

  @protected
  Network dco_decode_network(dynamic raw);

  @protected
  NewSeed dco_decode_new_seed(dynamic raw);

  @protected
  NodeChoice dco_decode_node_choice(dynamic raw);

  @protected
  NodeError dco_decode_node_error(dynamic raw);

  @protected
  NodeHealth dco_decode_node_health(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  SyncFailure? dco_decode_opt_box_autoadd_sync_failure(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  Payment dco_decode_payment(dynamic raw);

  @protected
  PaymentCheck dco_decode_payment_check(dynamic raw);

  @protected
  Preferences dco_decode_preferences(dynamic raw);

  @protected
  ProofFailure dco_decode_proof_failure(dynamic raw);

  @protected
  RequestRow dco_decode_request_row(dynamic raw);

  @protected
  RequestStatus dco_decode_request_status(dynamic raw);

  @protected
  RevealedKeys dco_decode_revealed_keys(dynamic raw);

  @protected
  ScanProgress dco_decode_scan_progress(dynamic raw);

  @protected
  SeedFormat dco_decode_seed_format(dynamic raw);

  @protected
  SendError dco_decode_send_error(dynamic raw);

  @protected
  SendSummary dco_decode_send_summary(dynamic raw);

  @protected
  ServerPaired dco_decode_server_paired(dynamic raw);

  @protected
  SyncEvent dco_decode_sync_event(dynamic raw);

  @protected
  SyncFailure dco_decode_sync_failure(dynamic raw);

  @protected
  SyncMode dco_decode_sync_mode(dynamic raw);

  @protected
  SyncPhase dco_decode_sync_phase(dynamic raw);

  @protected
  TxDetails dco_decode_tx_details(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WalletBalance dco_decode_wallet_balance(dynamic raw);

  @protected
  WalletError dco_decode_wallet_error(dynamic raw);

  @protected
  WalletSummary dco_decode_wallet_summary(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  ColdRequest
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColdRequest(
    SseDeserializer deserializer,
  );

  @protected
  ColdSend
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColdSend(
    SseDeserializer deserializer,
  );

  @protected
  FrameReader
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameReader(
    SseDeserializer deserializer,
  );

  @protected
  OpenWallet
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenWallet(
    SseDeserializer deserializer,
  );

  @protected
  PreparedSend
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPreparedSend(
    SseDeserializer deserializer,
  );

  @protected
  ColdRequest
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColdRequest(
    SseDeserializer deserializer,
  );

  @protected
  ColdSend
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColdSend(
    SseDeserializer deserializer,
  );

  @protected
  FrameReader
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameReader(
    SseDeserializer deserializer,
  );

  @protected
  OpenWallet
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenWallet(
    SseDeserializer deserializer,
  );

  @protected
  PreparedSend
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPreparedSend(
    SseDeserializer deserializer,
  );

  @protected
  ColdRequest
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColdRequest(
    SseDeserializer deserializer,
  );

  @protected
  ColdSend
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColdSend(
    SseDeserializer deserializer,
  );

  @protected
  FrameReader
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameReader(
    SseDeserializer deserializer,
  );

  @protected
  OpenWallet
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenWallet(
    SseDeserializer deserializer,
  );

  @protected
  PreparedSend
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPreparedSend(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SyncEvent> sse_decode_StreamSink_sync_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AddressKind sse_decode_address_kind(SseDeserializer deserializer);

  @protected
  AddressRow sse_decode_address_row(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  Preferences sse_decode_box_autoadd_preferences(SseDeserializer deserializer);

  @protected
  SyncFailure sse_decode_box_autoadd_sync_failure(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  CertificateDetails sse_decode_certificate_details(
    SseDeserializer deserializer,
  );

  @protected
  CoinRow sse_decode_coin_row(SseDeserializer deserializer);

  @protected
  ColdFailure sse_decode_cold_failure(SseDeserializer deserializer);

  @protected
  ColdImport sse_decode_cold_import(SseDeserializer deserializer);

  @protected
  ColdKind sse_decode_cold_kind(SseDeserializer deserializer);

  @protected
  ColdMessage sse_decode_cold_message(SseDeserializer deserializer);

  @protected
  ColdRequestSummary sse_decode_cold_request_summary(
    SseDeserializer deserializer,
  );

  @protected
  ContactRow sse_decode_contact_row(SseDeserializer deserializer);

  @protected
  CoreInfo sse_decode_core_info(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FeePriority sse_decode_fee_priority(SseDeserializer deserializer);

  @protected
  HistoryItem sse_decode_history_item(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AddressRow> sse_decode_list_address_row(SseDeserializer deserializer);

  @protected
  List<CoinRow> sse_decode_list_coin_row(SseDeserializer deserializer);

  @protected
  List<ContactRow> sse_decode_list_contact_row(SseDeserializer deserializer);

  @protected
  List<HistoryItem> sse_decode_list_history_item(SseDeserializer deserializer);

  @protected
  List<LocalNode> sse_decode_list_local_node(SseDeserializer deserializer);

  @protected
  List<Network> sse_decode_list_network(SseDeserializer deserializer);

  @protected
  List<NodeChoice> sse_decode_list_node_choice(SseDeserializer deserializer);

  @protected
  List<Payment> sse_decode_list_payment(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RequestRow> sse_decode_list_request_row(SseDeserializer deserializer);

  @protected
  List<WalletSummary> sse_decode_list_wallet_summary(
    SseDeserializer deserializer,
  );

  @protected
  LocalNode sse_decode_local_node(SseDeserializer deserializer);

  @protected
  LwsHealth sse_decode_lws_health(SseDeserializer deserializer);

  @protected
  Network sse_decode_network(SseDeserializer deserializer);

  @protected
  NewSeed sse_decode_new_seed(SseDeserializer deserializer);

  @protected
  NodeChoice sse_decode_node_choice(SseDeserializer deserializer);

  @protected
  NodeError sse_decode_node_error(SseDeserializer deserializer);

  @protected
  NodeHealth sse_decode_node_health(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  SyncFailure? sse_decode_opt_box_autoadd_sync_failure(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  Payment sse_decode_payment(SseDeserializer deserializer);

  @protected
  PaymentCheck sse_decode_payment_check(SseDeserializer deserializer);

  @protected
  Preferences sse_decode_preferences(SseDeserializer deserializer);

  @protected
  ProofFailure sse_decode_proof_failure(SseDeserializer deserializer);

  @protected
  RequestRow sse_decode_request_row(SseDeserializer deserializer);

  @protected
  RequestStatus sse_decode_request_status(SseDeserializer deserializer);

  @protected
  RevealedKeys sse_decode_revealed_keys(SseDeserializer deserializer);

  @protected
  ScanProgress sse_decode_scan_progress(SseDeserializer deserializer);

  @protected
  SeedFormat sse_decode_seed_format(SseDeserializer deserializer);

  @protected
  SendError sse_decode_send_error(SseDeserializer deserializer);

  @protected
  SendSummary sse_decode_send_summary(SseDeserializer deserializer);

  @protected
  ServerPaired sse_decode_server_paired(SseDeserializer deserializer);

  @protected
  SyncEvent sse_decode_sync_event(SseDeserializer deserializer);

  @protected
  SyncFailure sse_decode_sync_failure(SseDeserializer deserializer);

  @protected
  SyncMode sse_decode_sync_mode(SseDeserializer deserializer);

  @protected
  SyncPhase sse_decode_sync_phase(SseDeserializer deserializer);

  @protected
  TxDetails sse_decode_tx_details(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WalletBalance sse_decode_wallet_balance(SseDeserializer deserializer);

  @protected
  WalletError sse_decode_wallet_error(SseDeserializer deserializer);

  @protected
  WalletSummary sse_decode_wallet_summary(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColdRequest(
    ColdRequest self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColdSend(
    ColdSend self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameReader(
    FrameReader self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenWallet(
    OpenWallet self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPreparedSend(
    PreparedSend self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColdRequest(
    ColdRequest self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColdSend(
    ColdSend self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameReader(
    FrameReader self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenWallet(
    OpenWallet self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPreparedSend(
    PreparedSend self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColdRequest(
    ColdRequest self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColdSend(
    ColdSend self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameReader(
    FrameReader self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenWallet(
    OpenWallet self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPreparedSend(
    PreparedSend self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_sync_event_Sse(
    RustStreamSink<SyncEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_address_kind(AddressKind self, SseSerializer serializer);

  @protected
  void sse_encode_address_row(AddressRow self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_preferences(
    Preferences self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_sync_failure(
    SyncFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_certificate_details(
    CertificateDetails self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_coin_row(CoinRow self, SseSerializer serializer);

  @protected
  void sse_encode_cold_failure(ColdFailure self, SseSerializer serializer);

  @protected
  void sse_encode_cold_import(ColdImport self, SseSerializer serializer);

  @protected
  void sse_encode_cold_kind(ColdKind self, SseSerializer serializer);

  @protected
  void sse_encode_cold_message(ColdMessage self, SseSerializer serializer);

  @protected
  void sse_encode_cold_request_summary(
    ColdRequestSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_contact_row(ContactRow self, SseSerializer serializer);

  @protected
  void sse_encode_core_info(CoreInfo self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_fee_priority(FeePriority self, SseSerializer serializer);

  @protected
  void sse_encode_history_item(HistoryItem self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_address_row(
    List<AddressRow> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_coin_row(List<CoinRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_contact_row(
    List<ContactRow> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_history_item(
    List<HistoryItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_local_node(
    List<LocalNode> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_network(List<Network> self, SseSerializer serializer);

  @protected
  void sse_encode_list_node_choice(
    List<NodeChoice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_payment(List<Payment> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_request_row(
    List<RequestRow> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_wallet_summary(
    List<WalletSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_local_node(LocalNode self, SseSerializer serializer);

  @protected
  void sse_encode_lws_health(LwsHealth self, SseSerializer serializer);

  @protected
  void sse_encode_network(Network self, SseSerializer serializer);

  @protected
  void sse_encode_new_seed(NewSeed self, SseSerializer serializer);

  @protected
  void sse_encode_node_choice(NodeChoice self, SseSerializer serializer);

  @protected
  void sse_encode_node_error(NodeError self, SseSerializer serializer);

  @protected
  void sse_encode_node_health(NodeHealth self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_sync_failure(
    SyncFailure? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_payment(Payment self, SseSerializer serializer);

  @protected
  void sse_encode_payment_check(PaymentCheck self, SseSerializer serializer);

  @protected
  void sse_encode_preferences(Preferences self, SseSerializer serializer);

  @protected
  void sse_encode_proof_failure(ProofFailure self, SseSerializer serializer);

  @protected
  void sse_encode_request_row(RequestRow self, SseSerializer serializer);

  @protected
  void sse_encode_request_status(RequestStatus self, SseSerializer serializer);

  @protected
  void sse_encode_revealed_keys(RevealedKeys self, SseSerializer serializer);

  @protected
  void sse_encode_scan_progress(ScanProgress self, SseSerializer serializer);

  @protected
  void sse_encode_seed_format(SeedFormat self, SseSerializer serializer);

  @protected
  void sse_encode_send_error(SendError self, SseSerializer serializer);

  @protected
  void sse_encode_send_summary(SendSummary self, SseSerializer serializer);

  @protected
  void sse_encode_server_paired(ServerPaired self, SseSerializer serializer);

  @protected
  void sse_encode_sync_event(SyncEvent self, SseSerializer serializer);

  @protected
  void sse_encode_sync_failure(SyncFailure self, SseSerializer serializer);

  @protected
  void sse_encode_sync_mode(SyncMode self, SseSerializer serializer);

  @protected
  void sse_encode_sync_phase(SyncPhase self, SseSerializer serializer);

  @protected
  void sse_encode_tx_details(TxDetails self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_wallet_balance(WalletBalance self, SseSerializer serializer);

  @protected
  void sse_encode_wallet_error(WalletError self, SseSerializer serializer);

  @protected
  void sse_encode_wallet_summary(WalletSummary self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColdRequest(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColdRequest(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColdRequest(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColdRequest(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColdSend(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColdSend(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColdSend(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColdSend(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameReader(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameReader(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameReader(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameReader(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenWallet(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenWallet(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenWallet(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenWallet(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPreparedSend(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPreparedSend(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPreparedSend(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPreparedSend(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColdRequest(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColdRequest(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColdSend(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColdSend(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameReader(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameReader(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenWallet(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenWallet(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPreparedSend(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPreparedSend(
    int ptr,
  );
}
