// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/core.dart';
import 'api/network.dart';
import 'api/nodes.dart';
import 'api/sync.dart';
import 'api/wallets.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_OpenWalletPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenWallet;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  OpenWallet
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenWallet(
    dynamic raw,
  );

  @protected
  OpenWallet
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenWallet(
    dynamic raw,
  );

  @protected
  OpenWallet
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenWallet(
    dynamic raw,
  );

  @protected
  RustStreamSink<SyncEvent> dco_decode_StreamSink_sync_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AddressRow dco_decode_address_row(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  SyncFailure dco_decode_box_autoadd_sync_failure(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  CoreInfo dco_decode_core_info(dynamic raw);

  @protected
  HistoryItem dco_decode_history_item(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AddressRow> dco_decode_list_address_row(dynamic raw);

  @protected
  List<HistoryItem> dco_decode_list_history_item(dynamic raw);

  @protected
  List<Network> dco_decode_list_network(dynamic raw);

  @protected
  List<NodeChoice> dco_decode_list_node_choice(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<WalletSummary> dco_decode_list_wallet_summary(dynamic raw);

  @protected
  Network dco_decode_network(dynamic raw);

  @protected
  NewSeed dco_decode_new_seed(dynamic raw);

  @protected
  NodeChoice dco_decode_node_choice(dynamic raw);

  @protected
  NodeError dco_decode_node_error(dynamic raw);

  @protected
  NodeHealth dco_decode_node_health(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  SyncFailure? dco_decode_opt_box_autoadd_sync_failure(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  SeedFormat dco_decode_seed_format(dynamic raw);

  @protected
  SyncEvent dco_decode_sync_event(dynamic raw);

  @protected
  SyncFailure dco_decode_sync_failure(dynamic raw);

  @protected
  SyncMode dco_decode_sync_mode(dynamic raw);

  @protected
  SyncPhase dco_decode_sync_phase(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WalletBalance dco_decode_wallet_balance(dynamic raw);

  @protected
  WalletError dco_decode_wallet_error(dynamic raw);

  @protected
  WalletSummary dco_decode_wallet_summary(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  OpenWallet
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenWallet(
    SseDeserializer deserializer,
  );

  @protected
  OpenWallet
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenWallet(
    SseDeserializer deserializer,
  );

  @protected
  OpenWallet
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenWallet(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SyncEvent> sse_decode_StreamSink_sync_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AddressRow sse_decode_address_row(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  SyncFailure sse_decode_box_autoadd_sync_failure(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  CoreInfo sse_decode_core_info(SseDeserializer deserializer);

  @protected
  HistoryItem sse_decode_history_item(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AddressRow> sse_decode_list_address_row(SseDeserializer deserializer);

  @protected
  List<HistoryItem> sse_decode_list_history_item(SseDeserializer deserializer);

  @protected
  List<Network> sse_decode_list_network(SseDeserializer deserializer);

  @protected
  List<NodeChoice> sse_decode_list_node_choice(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<WalletSummary> sse_decode_list_wallet_summary(
    SseDeserializer deserializer,
  );

  @protected
  Network sse_decode_network(SseDeserializer deserializer);

  @protected
  NewSeed sse_decode_new_seed(SseDeserializer deserializer);

  @protected
  NodeChoice sse_decode_node_choice(SseDeserializer deserializer);

  @protected
  NodeError sse_decode_node_error(SseDeserializer deserializer);

  @protected
  NodeHealth sse_decode_node_health(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  SyncFailure? sse_decode_opt_box_autoadd_sync_failure(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  SeedFormat sse_decode_seed_format(SseDeserializer deserializer);

  @protected
  SyncEvent sse_decode_sync_event(SseDeserializer deserializer);

  @protected
  SyncFailure sse_decode_sync_failure(SseDeserializer deserializer);

  @protected
  SyncMode sse_decode_sync_mode(SseDeserializer deserializer);

  @protected
  SyncPhase sse_decode_sync_phase(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WalletBalance sse_decode_wallet_balance(SseDeserializer deserializer);

  @protected
  WalletError sse_decode_wallet_error(SseDeserializer deserializer);

  @protected
  WalletSummary sse_decode_wallet_summary(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenWallet(
    OpenWallet self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenWallet(
    OpenWallet self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenWallet(
    OpenWallet self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_sync_event_Sse(
    RustStreamSink<SyncEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_address_row(AddressRow self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_sync_failure(
    SyncFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_core_info(CoreInfo self, SseSerializer serializer);

  @protected
  void sse_encode_history_item(HistoryItem self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_address_row(
    List<AddressRow> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_history_item(
    List<HistoryItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_network(List<Network> self, SseSerializer serializer);

  @protected
  void sse_encode_list_node_choice(
    List<NodeChoice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_wallet_summary(
    List<WalletSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_network(Network self, SseSerializer serializer);

  @protected
  void sse_encode_new_seed(NewSeed self, SseSerializer serializer);

  @protected
  void sse_encode_node_choice(NodeChoice self, SseSerializer serializer);

  @protected
  void sse_encode_node_error(NodeError self, SseSerializer serializer);

  @protected
  void sse_encode_node_health(NodeHealth self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_sync_failure(
    SyncFailure? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_seed_format(SeedFormat self, SseSerializer serializer);

  @protected
  void sse_encode_sync_event(SyncEvent self, SseSerializer serializer);

  @protected
  void sse_encode_sync_failure(SyncFailure self, SseSerializer serializer);

  @protected
  void sse_encode_sync_mode(SyncMode self, SseSerializer serializer);

  @protected
  void sse_encode_sync_phase(SyncPhase self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_wallet_balance(WalletBalance self, SseSerializer serializer);

  @protected
  void sse_encode_wallet_error(WalletError self, SseSerializer serializer);

  @protected
  void sse_encode_wallet_summary(WalletSummary self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenWallet(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenWallet(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenWallet(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenWallet(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenWallet(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenWallet(
    int ptr,
  );
}
