// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'network.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_settings`, `read`, `settings_for`, `write_file`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`

/// The shortest passphrase [`export_backup`] accepts.
int backupPassphraseMinLength() =>
    RustLib.instance.api.crateApiBackupBackupPassphraseMinLength();

/// Writes the wallets `wallet_ids` to a backup at `path`, encrypted with
/// `passphrase`. No wallet needs to be unlocked. Returns the file's size in
/// bytes.
///
/// # Errors
///
/// See [`BackupError`].
Future<BigInt> exportBackup({
  required List<String> walletIds,
  required String passphrase,
  required String path,
}) => RustLib.instance.api.crateApiBackupExportBackup(
  walletIds: walletIds,
  passphrase: passphrase,
  path: path,
);

/// Opens the backup at `path` with `passphrase` and lists the wallets in
/// it, without adding them.
///
/// # Errors
///
/// See [`BackupError`].
Future<BackupSummary> readBackupSummary({
  required String path,
  required String passphrase,
}) => RustLib.instance.api.crateApiBackupReadBackupSummary(
  path: path,
  passphrase: passphrase,
);

/// Adds the wallets in the backup at `path` to the wallet list. Existing
/// wallets are never replaced: a restored wallet whose name is taken is
/// called "Name (restored)". Network settings from the backup fill in only
/// what this device has not chosen itself.
///
/// # Errors
///
/// See [`BackupError`].
Future<List<ImportedWallet>> importBackup({
  required String path,
  required String passphrase,
}) => RustLib.instance.api.crateApiBackupImportBackup(
  path: path,
  passphrase: passphrase,
);

/// One wallet in a backup, for the preview before importing.
class BackupEntry {
  final String name;
  final Network network;
  final bool viewOnly;
  final bool cold;

  const BackupEntry({
    required this.name,
    required this.network,
    required this.viewOnly,
    required this.cold,
  });

  @override
  int get hashCode =>
      name.hashCode ^ network.hashCode ^ viewOnly.hashCode ^ cold.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackupEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          network == other.network &&
          viewOnly == other.viewOnly &&
          cold == other.cold;
}

/// Why a backup could not be written or read. The app maps each case to
/// its own message.
enum BackupError {
  /// Shorter than [`backup_passphrase_min_length`].
  shortPassphrase,
  wrongPassphrase,

  /// Not a Kilonova backup, or a damaged one.
  notABackup,

  /// Written by a newer version of Kilonova.
  newerVersion,

  /// No wallets were chosen.
  noWallets,

  /// A chosen wallet does not exist.
  notFound,

  /// The file could not be written or read.
  storage,
  notInitialized,
}

/// What a backup holds.
class BackupSummary {
  final List<BackupEntry> wallets;
  final int count;

  const BackupSummary({required this.wallets, required this.count});

  @override
  int get hashCode => wallets.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackupSummary &&
          runtimeType == other.runtimeType &&
          wallets == other.wallets &&
          count == other.count;
}

/// A wallet added from a backup.
class ImportedWallet {
  final String id;

  /// Its name in the list now.
  final String name;

  /// Its name in the backup; differs from `name` when a wallet of that
  /// name already existed, which is kept as it was.
  final String originalName;
  final Network network;

  const ImportedWallet({
    required this.id,
    required this.name,
    required this.originalName,
    required this.network,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ originalName.hashCode ^ network.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportedWallet &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          originalName == other.originalName &&
          network == other.network;
}
