// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`, `from`

/// The watch state for wallet `id`, after checking `password`: its
/// primary address, private view key and public spend key, where its sync
/// has got to, and the node (full mode) or the light wallet server it
/// already shares the view key with (LWS mode). Never the spend key or the
/// seed. The app hands it to the platform, which keeps it encrypted.
///
/// # Errors
///
/// [`BackgroundError::WrongPassword`] for a wrong password,
/// [`BackgroundError::Cold`] for an offline wallet,
/// [`BackgroundError::LwsConsentNeeded`] for an LWS-mode wallet not yet
/// agreed with the current server.
Future<Uint8List> exportWatchState({
  required String id,
  required String password,
}) => RustLib.instance.api.crateApiBackgroundExportWatchState(
  id: id,
  password: password,
);

enum BackgroundError {
  wrongPassword,
  notFound,

  /// An offline wallet never goes online, not even to check.
  cold,

  /// An LWS-mode wallet whose owner has not agreed to share the view key
  /// with the light wallet server now set (or none is set).
  lwsConsentNeeded,
  storage,
  notInitialized,
}
