// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'send.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

/// A saved recipient.
class ContactRow {
  final String name;
  final String address;

  const ContactRow({required this.name, required this.address});

  @override
  int get hashCode => name.hashCode ^ address.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContactRow &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          address == other.address;
}

/// What the wallet knows about one transaction beyond the chain.
class TxDetails {
  /// The owner's note; empty if none.
  final String note;

  /// For transactions sent from this wallet: who was paid what.
  final List<Payment> destinations;

  /// A transaction key is stored and can be revealed for a payment proof.
  final bool hasTxKey;

  const TxDetails({
    required this.note,
    required this.destinations,
    required this.hasTxKey,
  });

  @override
  int get hashCode => note.hashCode ^ destinations.hashCode ^ hasTxKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TxDetails &&
          runtimeType == other.runtimeType &&
          note == other.note &&
          destinations == other.destinations &&
          hasTxKey == other.hasTxKey;
}
