// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

/// One unspent output.
class CoinRow {
  /// One-time output key (hex): the coin's identity.
  final String key;

  /// Atomic units.
  final BigInt amount;

  /// Block it arrived in.
  final BigInt height;

  /// Subaddress index in account 0 it arrived on (0 is the primary).
  final int subaddressIndex;
  final bool miner;

  /// Cannot be spent yet.
  final bool locked;

  /// The owner froze it: never spent until thawed.
  final bool frozen;

  /// The transaction it arrived in (hex).
  final String txHash;

  const CoinRow({
    required this.key,
    required this.amount,
    required this.height,
    required this.subaddressIndex,
    required this.miner,
    required this.locked,
    required this.frozen,
    required this.txHash,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      amount.hashCode ^
      height.hashCode ^
      subaddressIndex.hashCode ^
      miner.hashCode ^
      locked.hashCode ^
      frozen.hashCode ^
      txHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoinRow &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          amount == other.amount &&
          height == other.height &&
          subaddressIndex == other.subaddressIndex &&
          miner == other.miner &&
          locked == other.locked &&
          frozen == other.frozen &&
          txHash == other.txHash;
}
