// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'send.dart';
import 'wallets.dart';

// These functions are ignored because they are not marked as `pub`: `lock`, `of`, `signer`, `watching`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`

/// What kind of message `message` (a whole scan or file) is.
///
/// # Errors
///
/// [`ColdFailure::NotColdData`] for anything else.
ColdKind coldMessageKind({required List<int> message}) =>
    RustLib.instance.api.crateApiColdColdMessageKind(message: message);

/// Creates the watching wallet for a cold wallet, from its pairing message.
///
/// # Errors
///
/// [`ColdFailure::WrongKind`] for any other message, or what creating a
/// view-only wallet can fail with.
Future<OpenWallet> createWatchingWallet({
  required String name,
  required List<int> message,
  required String password,
  required SyncMode mode,
}) => RustLib.instance.api.crateApiColdCreateWatchingWallet(
  name: name,
  message: message,
  password: password,
  mode: mode,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ColdRequest>>
abstract class ColdRequest implements RustOpaqueInterface {
  ColdRequestSummary summary();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ColdSend>>
abstract class ColdSend implements RustOpaqueInterface {
  /// The sign request to show to the cold wallet.
  ColdMessage message();

  SendSummary summary();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FrameReader>>
abstract class FrameReader implements RustOpaqueInterface {
  /// Adds one scanned code.
  ///
  /// # Errors
  ///
  /// [`ColdFailure::NotColdData`] for a code that is not part of a
  /// Kilonova message.
  ScanProgress add({required String frame});

  static Future<FrameReader> default_() =>
      RustLib.instance.api.crateApiColdFrameReaderDefault();

  /// The whole message, once complete.
  ///
  /// # Errors
  ///
  /// [`ColdFailure::Damaged`] if parts are missing or do not match.
  Uint8List message();

  factory FrameReader() => RustLib.instance.api.crateApiColdFrameReaderNew();
}

/// Why a cold wallet step failed. The app maps each case to its own message.
enum ColdFailure {
  /// Not a Kilonova cold wallet code or file.
  notColdData,

  /// Meant for another wallet.
  wrongWallet,

  /// Meant for another network.
  wrongNetwork,

  /// The wrong step: for example a signed answer scanned on the cold wallet.
  wrongKind,

  /// Missing parts or damaged; scan again.
  damaged,

  /// The transaction spends coins that are not this wallet's.
  notOurs,

  /// The transaction's change goes somewhere else.
  changeElsewhere,
  badAddress,
  feeTooHigh,

  /// The amounts do not add up.
  inconsistent,

  /// Only a wallet with its spend key can do this.
  viewOnly,

  /// Only a view-only wallet does this; this one can sign itself.
  notWatching,

  /// A cold wallet never goes online.
  isCold,
  wrongPassword,

  /// The prepared request was already answered or discarded.
  alreadyUsed,

  /// Building or publishing failed; the details are in [`SendError`].
  send,
  locked,
  storage,
}

/// What importing a cold wallet's answer did.
class ColdImport {
  /// Coins whose key images the watching wallet learned.
  final int keyImages;

  /// The published transaction, for a signed answer.
  final String? publishedTx;

  const ColdImport({required this.keyImages, this.publishedTx});

  @override
  int get hashCode => keyImages.hashCode ^ publishedTx.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ColdImport &&
          runtimeType == other.runtimeType &&
          keyImages == other.keyImages &&
          publishedTx == other.publishedTx;
}

/// What a message is, so the app can route a scan to the right screen.
enum ColdKind { pairing, syncRequest, syncAnswer, signRequest, signed }

/// A message ready to show or save.
class ColdMessage {
  final ColdKind kind;

  /// QR codes to show in turn; one when it fits.
  final List<String> frames;

  /// The same message as a file, for moving by USB or SD card.
  final Uint8List file;

  const ColdMessage({
    required this.kind,
    required this.frames,
    required this.file,
  });

  @override
  int get hashCode => kind.hashCode ^ frames.hashCode ^ file.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ColdMessage &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          frames == other.frames &&
          file == other.file;
}

/// What a cold wallet is asked to do, for its confirmation screen.
class ColdRequestSummary {
  final ColdKind kind;

  /// For a sign request: who is paid what, read from the transaction.
  final List<Payment> payments;
  final BigInt fee;

  /// Coming back to this wallet.
  final BigInt change;

  /// Coins it spends.
  final int inputs;

  const ColdRequestSummary({
    required this.kind,
    required this.payments,
    required this.fee,
    required this.change,
    required this.inputs,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      payments.hashCode ^
      fee.hashCode ^
      change.hashCode ^
      inputs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ColdRequestSummary &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          payments == other.payments &&
          fee == other.fee &&
          change == other.change &&
          inputs == other.inputs;
}

/// How far a multi-part scan has come.
class ScanProgress {
  final int received;
  final int total;
  final bool complete;

  const ScanProgress({
    required this.received,
    required this.total,
    required this.complete,
  });

  @override
  int get hashCode => received.hashCode ^ total.hashCode ^ complete.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanProgress &&
          runtimeType == other.runtimeType &&
          received == other.received &&
          total == other.total &&
          complete == other.complete;
}
