// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`, `from`, `from`, `hash`

/// All networks, in the order the network switcher shows them.
List<Network> allNetworks() =>
    RustLib.instance.api.crateApiNetworkAllNetworks();

/// The Monero network a wallet belongs to.
///
/// A wallet's network is fixed when it is created, because address prefixes
/// differ between networks. Stagenet and testnet coins have no value.
enum Network {
  mainnet,
  stagenet,
  testnet;

  /// True for networks whose coins have no value.
  bool isTestNetwork() =>
      RustLib.instance.api.crateApiNetworkNetworkIsTestNetwork(that: this);
}
