// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'network.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `current_node`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// Bundled and user-added nodes for `network`, with the selected one marked.
///
/// # Errors
///
/// Fails if the settings cannot be read.
Future<List<NodeChoice>> nodes({required Network network}) =>
    RustLib.instance.api.crateApiNodesNodes(network: network);

/// Adds a node the user trusts and selects it. Returns the normalized URL.
///
/// # Errors
///
/// [`NodeError::BadUrl`] for anything that is not `host:port` or an
/// http(s) URL.
Future<String> addNode({required Network network, required String url}) =>
    RustLib.instance.api.crateApiNodesAddNode(network: network, url: url);

/// Removes a user-added node. If it was selected, a bundled node is picked
/// next time.
///
/// # Errors
///
/// Fails if the settings cannot be written.
Future<void> removeNode({required Network network, required String url}) =>
    RustLib.instance.api.crateApiNodesRemoveNode(network: network, url: url);

/// Makes `url` the node `network` syncs from.
///
/// # Errors
///
/// [`NodeError::BadUrl`] if it is not a valid node address.
Future<void> selectNode({required Network network, required String url}) =>
    RustLib.instance.api.crateApiNodesSelectNode(network: network, url: url);

/// Connects to `url` and checks it serves `network`.
///
/// # Errors
///
/// [`NodeError::WrongNetwork`] or [`NodeError::Unreachable`].
Future<NodeHealth> checkNode({required Network network, required String url}) =>
    RustLib.instance.api.crateApiNodesCheckNode(network: network, url: url);

/// The light wallet server LWS-mode wallets on `network` use, if one is
/// set. Kilonova never picks one.
///
/// # Errors
///
/// Fails if the settings cannot be read.
Future<String?> lwsServer({required Network network}) =>
    RustLib.instance.api.crateApiNodesLwsServer(network: network);

/// Sets the light wallet server for `network`. Returns the normalized URL.
///
/// # Errors
///
/// [`NodeError::BadUrl`] for anything that is not `host:port` or an
/// http(s) URL.
Future<String> setLwsServer({required Network network, required String url}) =>
    RustLib.instance.api.crateApiNodesSetLwsServer(network: network, url: url);

/// Forgets the light wallet server for `network`.
///
/// # Errors
///
/// Fails if the settings cannot be written.
Future<void> clearLwsServer({required Network network}) =>
    RustLib.instance.api.crateApiNodesClearLwsServer(network: network);

/// Contacts a light wallet server and checks its network where it says.
/// Sends no keys.
///
/// # Errors
///
/// [`NodeError::WrongNetwork`] or [`NodeError::Unreachable`].
Future<LwsHealth> checkLwsServer({
  required Network network,
  required String url,
}) => RustLib.instance.api.crateApiNodesCheckLwsServer(
  network: network,
  url: url,
);

/// What a light wallet server reported when checked.
class LwsHealth {
  final BigInt height;
  final String? serverType;

  const LwsHealth({required this.height, this.serverType});

  @override
  int get hashCode => height.hashCode ^ serverType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LwsHealth &&
          runtimeType == other.runtimeType &&
          height == other.height &&
          serverType == other.serverType;
}

/// A node as listed in settings.
class NodeChoice {
  final String url;

  /// Shipped with the app (run by a third party) rather than added by
  /// the user.
  final bool bundled;
  final bool selected;

  const NodeChoice({
    required this.url,
    required this.bundled,
    required this.selected,
  });

  @override
  int get hashCode => url.hashCode ^ bundled.hashCode ^ selected.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NodeChoice &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          bundled == other.bundled &&
          selected == other.selected;
}

enum NodeError { badUrl, wrongNetwork, unreachable, storage, notInitialized }

/// What a node reported when checked.
class NodeHealth {
  final BigInt height;
  final bool synced;

  const NodeHealth({required this.height, required this.synced});

  @override
  int get hashCode => height.hashCode ^ synced.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NodeHealth &&
          runtimeType == other.runtimeType &&
          height == other.height &&
          synced == other.synced;
}
