// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'network.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_saved_network_settings`, `apply_saved_pins`, `colon_hex`, `current_node`, `explain`, `parse_fingerprint`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// Bundled and user-added nodes for `network`, with the selected one marked.
///
/// # Errors
///
/// Fails if the settings cannot be read.
Future<List<NodeChoice>> nodes({required Network network}) =>
    RustLib.instance.api.crateApiNodesNodes(network: network);

/// Adds a node the user trusts and selects it. Returns the normalized URL.
///
/// # Errors
///
/// [`NodeError::BadUrl`] for anything that is not `host:port` or an
/// http(s) URL.
Future<String> addNode({required Network network, required String url}) =>
    RustLib.instance.api.crateApiNodesAddNode(network: network, url: url);

/// Removes a user-added node. If it was selected, a bundled node is picked
/// next time.
///
/// # Errors
///
/// Fails if the settings cannot be written.
Future<void> removeNode({required Network network, required String url}) =>
    RustLib.instance.api.crateApiNodesRemoveNode(network: network, url: url);

/// Makes `url` the node `network` syncs from.
///
/// # Errors
///
/// [`NodeError::BadUrl`] if it is not a valid node address.
Future<void> selectNode({required Network network, required String url}) =>
    RustLib.instance.api.crateApiNodesSelectNode(network: network, url: url);

/// Connects to `url` and checks it serves `network`.
///
/// # Errors
///
/// [`NodeError::WrongNetwork`] or [`NodeError::Unreachable`].
Future<NodeHealth> checkNode({required Network network, required String url}) =>
    RustLib.instance.api.crateApiNodesCheckNode(network: network, url: url);

/// The light wallet server LWS-mode wallets on `network` use, if one is
/// set. Kilonova never picks one.
///
/// # Errors
///
/// Fails if the settings cannot be read.
Future<String?> lwsServer({required Network network}) =>
    RustLib.instance.api.crateApiNodesLwsServer(network: network);

/// Sets the light wallet server for `network`. Returns the normalized URL.
///
/// # Errors
///
/// [`NodeError::BadUrl`] for anything that is not `host:port` or an
/// http(s) URL.
Future<String> setLwsServer({required Network network, required String url}) =>
    RustLib.instance.api.crateApiNodesSetLwsServer(network: network, url: url);

/// Forgets the light wallet server for `network`.
///
/// # Errors
///
/// Fails if the settings cannot be written.
Future<void> clearLwsServer({required Network network}) =>
    RustLib.instance.api.crateApiNodesClearLwsServer(network: network);

/// Contacts a light wallet server and checks its network where it says.
/// Sends no keys.
///
/// # Errors
///
/// [`NodeError::WrongNetwork`] or [`NodeError::Unreachable`].
Future<LwsHealth> checkLwsServer({
  required Network network,
  required String url,
}) => RustLib.instance.api.crateApiNodesCheckLwsServer(
  network: network,
  url: url,
);

/// Reads the certificate an https node or server presents, without sending
/// it anything.
///
/// # Errors
///
/// [`NodeError::BadUrl`] for an http address, [`NodeError::Unreachable`]
/// if no certificate could be read.
Future<CertificateDetails> serverCertificateInfo({required String url}) =>
    RustLib.instance.api.crateApiNodesServerCertificateInfo(url: url);

/// Trusts `url` for the certificate with `fingerprint` (as returned by
/// [`server_certificate_info`]) and nothing else.
///
/// # Errors
///
/// [`NodeError::BadUrl`] for a bad address or fingerprint.
Future<void> trustCertificate({
  required String url,
  required String fingerprint,
}) => RustLib.instance.api.crateApiNodesTrustCertificate(
  url: url,
  fingerprint: fingerprint,
);

/// Removes the pinned certificate for `url`.
///
/// # Errors
///
/// Fails if the settings cannot be saved.
Future<void> forgetCertificate({required String url}) =>
    RustLib.instance.api.crateApiNodesForgetCertificate(url: url);

/// Uses the node and light wallet server a self-hosted server's pairing
/// code names (see `tools/selfhost`).
///
/// # Errors
///
/// [`NodeError::BadUrl`] for anything that is not a pairing code.
Future<ServerPaired> pairWithServer({required String code}) =>
    RustLib.instance.api.crateApiNodesPairWithServer(code: code);

/// Looks for nodes serving `network` on this machine and the local network
/// (the standard RPC ports on the local /24). Takes a few seconds.
///
/// # Errors
///
/// [`NodeError::ProxyOn`] while a proxy is set: the scan cannot go through
/// it, and would show the local network what the owner is looking for.
Future<List<LocalNode>> findLocalNodes({required Network network}) =>
    RustLib.instance.api.crateApiNodesFindLocalNodes(network: network);

/// The SOCKS5 proxy (for example Tor) all traffic goes through, if any.
///
/// # Errors
///
/// Fails if the settings cannot be read.
Future<String?> networkProxy() =>
    RustLib.instance.api.crateApiNodesNetworkProxy();

/// Sends all traffic through `url` from now on, or directly with `None`,
/// and remembers the choice. Returns the normalized address. Restart sync
/// afterwards.
///
/// # Errors
///
/// [`NodeError::BadProxy`] for an invalid address.
Future<String?> setNetworkProxy({String? url}) =>
    RustLib.instance.api.crateApiNodesSetNetworkProxy(url: url);

/// Checks that a SOCKS5 proxy answers at `url`, without sending anything
/// through it.
///
/// # Errors
///
/// [`NodeError::BadProxy`] or [`NodeError::Unreachable`].
Future<String> checkNetworkProxy({required String url}) =>
    RustLib.instance.api.crateApiNodesCheckNetworkProxy(url: url);

/// A server's certificate, for the user to compare before trusting it.
class CertificateDetails {
  /// SHA-256 of the certificate, as colon-separated hex pairs.
  final String fingerprint;

  /// Issued by a public authority, so no pin is needed.
  final bool publiclyTrusted;

  /// The pinned fingerprint for this address, if any.
  final String? pinned;

  const CertificateDetails({
    required this.fingerprint,
    required this.publiclyTrusted,
    this.pinned,
  });

  @override
  int get hashCode =>
      fingerprint.hashCode ^ publiclyTrusted.hashCode ^ pinned.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CertificateDetails &&
          runtimeType == other.runtimeType &&
          fingerprint == other.fingerprint &&
          publiclyTrusted == other.publiclyTrusted &&
          pinned == other.pinned;
}

/// A node found on the local network.
class LocalNode {
  final String url;
  final BigInt height;
  final bool synced;

  const LocalNode({
    required this.url,
    required this.height,
    required this.synced,
  });

  @override
  int get hashCode => url.hashCode ^ height.hashCode ^ synced.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalNode &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          height == other.height &&
          synced == other.synced;
}

/// What a light wallet server reported when checked.
class LwsHealth {
  final BigInt height;
  final String? serverType;

  const LwsHealth({required this.height, this.serverType});

  @override
  int get hashCode => height.hashCode ^ serverType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LwsHealth &&
          runtimeType == other.runtimeType &&
          height == other.height &&
          serverType == other.serverType;
}

/// A node as listed in settings.
class NodeChoice {
  final String url;

  /// Shipped with the app (run by a third party) rather than added by
  /// the user.
  final bool bundled;
  final bool selected;

  /// Trusted through a pinned certificate.
  final bool pinned;

  const NodeChoice({
    required this.url,
    required this.bundled,
    required this.selected,
    required this.pinned,
  });

  @override
  int get hashCode =>
      url.hashCode ^ bundled.hashCode ^ selected.hashCode ^ pinned.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NodeChoice &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          bundled == other.bundled &&
          selected == other.selected &&
          pinned == other.pinned;
}

enum NodeError {
  badUrl,
  wrongNetwork,
  unreachable,
  storage,
  notInitialized,

  /// Not a valid proxy address.
  badProxy,

  /// An onion address without a Tor proxy set.
  needsTor,

  /// The server's certificate is not from a public authority (or not the
  /// one pinned). See [`server_certificate_info`].
  untrustedCertificate,

  /// A light wallet server on plain http elsewhere than this device.
  insecureLws,

  /// Looking on the local network would bypass the proxy the owner set.
  proxyOn,
}

/// What a node reported when checked.
class NodeHealth {
  final BigInt height;
  final bool synced;

  const NodeHealth({required this.height, required this.synced});

  @override
  int get hashCode => height.hashCode ^ synced.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NodeHealth &&
          runtimeType == other.runtimeType &&
          height == other.height &&
          synced == other.synced;
}

/// What pairing with a self-hosted server set.
class ServerPaired {
  final Network network;

  /// The node now selected for that network, if the code named one.
  final String? node;

  /// The light wallet server now set, if the code named one.
  final String? lws;

  /// The addresses are onion services and no Tor proxy is set yet.
  final bool needsTor;

  const ServerPaired({
    required this.network,
    this.node,
    this.lws,
    required this.needsTor,
  });

  @override
  int get hashCode =>
      network.hashCode ^ node.hashCode ^ lws.hashCode ^ needsTor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerPaired &&
          runtimeType == other.runtimeType &&
          network == other.network &&
          node == other.node &&
          lws == other.lws &&
          needsTor == other.needsTor;
}
