// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'nodes.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

/// # Errors
///
/// Fails if the settings cannot be read.
Future<Preferences> preferences() =>
    RustLib.instance.api.crateApiPreferencesPreferences();

/// # Errors
///
/// Fails if the settings cannot be saved.
Future<void> setPreferences({required Preferences preferences}) => RustLib
    .instance
    .api
    .crateApiPreferencesSetPreferences(preferences: preferences);

class Preferences {
  /// Show a notification for incoming payments while the app is not in
  /// front.
  final bool notifyIncoming;

  /// Android: keep unlocked wallets syncing in the background instead of
  /// locking them when the app leaves the screen.
  final bool backgroundSync;

  /// LWS-mode wallets confirm each payment the server reports with the
  /// network's node (through the proxy). Each lookup is hidden among
  /// cover lookups, so it is on by default.
  final bool confirmLwsPayments;

  const Preferences({
    required this.notifyIncoming,
    required this.backgroundSync,
    required this.confirmLwsPayments,
  });

  @override
  int get hashCode =>
      notifyIncoming.hashCode ^
      backgroundSync.hashCode ^
      confirmLwsPayments.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Preferences &&
          runtimeType == other.runtimeType &&
          notifyIncoming == other.notifyIncoming &&
          backgroundSync == other.backgroundSync &&
          confirmLwsPayments == other.confirmLwsPayments;
}
