// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'nodes.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Currencies prices can be shown in, as lower-case ISO 4217 codes.
List<String> priceCurrencies() =>
    RustLib.instance.api.crateApiPricePriceCurrencies();

/// The service prices come from, for the settings screen.
String priceSource() => RustLib.instance.api.crateApiPricePriceSource();

/// The chosen currency, or `None` while prices are off.
///
/// # Errors
///
/// Fails if the settings cannot be read.
Future<String?> priceCurrency() =>
    RustLib.instance.api.crateApiPricePriceCurrency();

/// Turns prices on in `currency`, or off with `None`.
///
/// # Errors
///
/// [`NodeError::BadUrl`] for a currency not in [`price_currencies`].
Future<void> setPriceCurrency({String? currency}) =>
    RustLib.instance.api.crateApiPriceSetPriceCurrency(currency: currency);

/// The price of 1 XMR in the chosen currency. `None` while prices are off,
/// in which case nothing is fetched.
///
/// # Errors
///
/// [`NodeError::Unreachable`] if the price service does not answer.
Future<double?> fetchXmrPrice() =>
    RustLib.instance.api.crateApiPriceFetchXmrPrice();
