// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'network.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `load`, `remember_server`, `save`, `subscription`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Stored`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `from`, `from`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

/// The push server the pairing code for `network` named, if any.
///
/// # Errors
///
/// Fails if the settings cannot be read.
Future<String?> pushServer({required Network network}) =>
    RustLib.instance.api.crateApiPushPushServer(network: network);

/// Every wallet's push topic.
///
/// # Errors
///
/// Fails if the settings cannot be read.
Future<List<PushSubscription>> pushSubscriptions() =>
    RustLib.instance.api.crateApiPushPushSubscriptions();

/// Sets `wallet_id`'s push topic from the code `push-register` printed.
/// A code without a server uses the one paired for `network`.
///
/// # Errors
///
/// [`PushError::BadCode`] or [`PushError::NoServer`].
Future<PushSubscription> setPushSubscription({
  required String walletId,
  required Network network,
  required String code,
}) => RustLib.instance.api.crateApiPushSetPushSubscription(
  walletId: walletId,
  network: network,
  code: code,
);

/// Forgets `wallet_id`'s push topic.
///
/// # Errors
///
/// Fails if the settings cannot be saved.
Future<void> removePushSubscription({required String walletId}) =>
    RustLib.instance.api.crateApiPushRemovePushSubscription(walletId: walletId);

/// Asks the server to repeat `wallet_id`'s pushes on a phone's `UnifiedPush`
/// `endpoint`, which must be on the same server. Goes through the proxy,
/// on the wallet's sync circuit (the server is the wallet's own).
///
/// # Errors
///
/// [`PushError::WrongServer`] for an endpoint elsewhere; otherwise as
/// [`PushError`] says.
Future<void> bindPushEndpoint({
  required String walletId,
  required String endpoint,
}) => RustLib.instance.api.crateApiPushBindPushEndpoint(
  walletId: walletId,
  endpoint: endpoint,
);

/// Looks for pushes on `wallet_id`'s topic since `since` (an id from the
/// last poll, or a Unix time in seconds), through the proxy.
///
/// # Errors
///
/// As [`PushError`] says.
Future<PushPoll> pollPush({required String walletId, required String since}) =>
    RustLib.instance.api.crateApiPushPollPush(walletId: walletId, since: since);

enum PushError {
  /// Not a push code.
  badCode,

  /// The code names no server, and no paired server has one.
  noServer,

  /// The `UnifiedPush` distributor uses a server other than the wallet's
  /// own; pushes would pass through a third party.
  wrongServer,

  /// An onion server without a Tor proxy set.
  needsTor,

  /// The server or its relay could not be reached, or refused.
  unreachable,

  /// The wallet has no push topic.
  notSet,
  storage,
  notInitialized,
}

/// What [`poll_push`] found.
class PushPoll {
  /// Pushes since `since`.
  final int arrived;

  /// What to pass as `since` next time.
  final String since;

  const PushPoll({required this.arrived, required this.since});

  @override
  int get hashCode => arrived.hashCode ^ since.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PushPoll &&
          runtimeType == other.runtimeType &&
          arrived == other.arrived &&
          since == other.since;
}

/// A wallet's push topic and the server (ntfy) it is on.
class PushSubscription {
  final String walletId;
  final String server;
  final String topic;

  const PushSubscription({
    required this.walletId,
    required this.server,
    required this.topic,
  });

  @override
  int get hashCode => walletId.hashCode ^ server.hashCode ^ topic.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PushSubscription &&
          runtimeType == other.runtimeType &&
          walletId == other.walletId &&
          server == other.server &&
          topic == other.topic;
}
