// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decimal_xmr`, `now`, `percent_encode`, `request_row`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

/// One payment request and how it stands.
class RequestRow {
  final String id;

  /// The subaddress made for it.
  final String address;

  /// A `monero:` link with the amount and label, for a QR code.
  final String uri;

  /// Atomic units asked for.
  final BigInt amount;
  final String label;
  final BigInt createdAt;
  final BigInt? expiresAt;

  /// Received in blocks so far.
  final BigInt received;

  /// Waiting in the pool.
  final BigInt arriving;
  final RequestStatus status;

  const RequestRow({
    required this.id,
    required this.address,
    required this.uri,
    required this.amount,
    required this.label,
    required this.createdAt,
    this.expiresAt,
    required this.received,
    required this.arriving,
    required this.status,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      address.hashCode ^
      uri.hashCode ^
      amount.hashCode ^
      label.hashCode ^
      createdAt.hashCode ^
      expiresAt.hashCode ^
      received.hashCode ^
      arriving.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RequestRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          address == other.address &&
          uri == other.uri &&
          amount == other.amount &&
          label == other.label &&
          createdAt == other.createdAt &&
          expiresAt == other.expiresAt &&
          received == other.received &&
          arriving == other.arriving &&
          status == other.status;
}

enum RequestStatus {
  /// Nothing received yet.
  waiting,

  /// A payment is in the pool, not yet in a block.
  arriving,

  /// Less than asked was received.
  partial,

  /// At least the amount asked was received.
  paid,

  /// Expired before being paid.
  expired,
}
