// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'network.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `for_wallet`, `parse_keys`, `prepare_send_inner`, `prepare_unsigned`, `prepare`, `publish_signed`, `publish`, `url`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Route`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`

/// Checks an address for `network` without a wallet.
///
/// # Errors
///
/// [`SendError::BadAddress`] if it is not a valid address on `network`.
AddressKind checkAddress({required String address, required Network network}) =>
    RustLib.instance.api.crateApiSendCheckAddress(
      address: address,
      network: network,
    );

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PreparedSend>>
abstract class PreparedSend implements RustOpaqueInterface {
  SendSummary summary();
}

enum AddressKind { standard, subaddress, integrated }

enum FeePriority { low, normal, high, urgent }

/// One recipient.
class Payment {
  final String address;

  /// Atomic units.
  final BigInt amount;

  const Payment({required this.address, required this.amount});

  @override
  int get hashCode => address.hashCode ^ amount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Payment &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          amount == other.amount;
}

/// Why sending failed. The app maps each case to its own message.
enum SendError {
  badAddress,
  zeroAmount,
  tooManyPayments,
  insufficientFunds,
  tooManyInputs,
  viewOnly,

  /// The node or server suggested an absurd fee rate.
  feeTooHigh,

  /// Sync has not reached the chain tip yet.
  notSynced,

  /// The node or light wallet server could not be reached or could not
  /// provide decoys or fees.
  unreachable,

  /// The network refused the transaction.
  rejected,

  /// The transaction could not be built.
  build,
  lwsServerNotSet,
  lwsConsentNeeded,
  wrongPassword,

  /// This prepared transaction was already published or discarded.
  alreadyUsed,

  /// The wallet was locked.
  locked,
  storage,
}

/// What a prepared transaction will do, for the confirmation screen.
class SendSummary {
  final String txHash;

  /// Recipients with what each receives. For a sweep, the one recipient
  /// receives everything minus the fee.
  final List<Payment> payments;
  final BigInt fee;

  /// Returned to this wallet.
  final BigInt change;

  /// The node or light wallet server that will publish it.
  final String via;

  /// How many of this wallet's addresses the spent coins arrived on. More
  /// than one lets whoever paid them see they belong to one wallet.
  final int linkedAddresses;

  const SendSummary({
    required this.txHash,
    required this.payments,
    required this.fee,
    required this.change,
    required this.via,
    required this.linkedAddresses,
  });

  @override
  int get hashCode =>
      txHash.hashCode ^
      payments.hashCode ^
      fee.hashCode ^
      change.hashCode ^
      via.hashCode ^
      linkedAddresses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendSummary &&
          runtimeType == other.runtimeType &&
          txHash == other.txHash &&
          payments == other.payments &&
          fee == other.fee &&
          change == other.change &&
          via == other.via &&
          linkedAddresses == other.linkedAddresses;
}
