// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'network.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `caught_up_state`, `emit`, `fail`, `failed`, `full_round`, `go`, `hex_string`, `is_current`, `load`, `lock_current`, `lock_state`, `lws_round`, `new`, `pause`, `record`, `replace`, `reset`, `snapshot`, `starting_state`, `stop`, `stopped`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Run`, `Setup`, `SyncHandle`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// A block height to record as the restore height of a wallet created now,
/// so a new wallet does not scan old blocks.
BigInt restoreHeightForNewWallet({required Network network}) => RustLib
    .instance
    .api
    .crateApiSyncRestoreHeightForNewWallet(network: network);

class HistoryItem {
  final String txHash;
  final BigInt height;
  final bool incoming;

  /// Atomic units.
  final BigInt amount;
  final bool miner;

  /// True while the received funds cannot be spent yet.
  final bool locked;

  /// Index of the first receiving subaddress in its account, if incoming.
  final int? subaddressIndex;

  /// Outgoing and not yet seen in a block.
  final bool pending;

  const HistoryItem({
    required this.txHash,
    required this.height,
    required this.incoming,
    required this.amount,
    required this.miner,
    required this.locked,
    this.subaddressIndex,
    required this.pending,
  });

  @override
  int get hashCode =>
      txHash.hashCode ^
      height.hashCode ^
      incoming.hashCode ^
      amount.hashCode ^
      miner.hashCode ^
      locked.hashCode ^
      subaddressIndex.hashCode ^
      pending.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistoryItem &&
          runtimeType == other.runtimeType &&
          txHash == other.txHash &&
          height == other.height &&
          incoming == other.incoming &&
          amount == other.amount &&
          miner == other.miner &&
          locked == other.locked &&
          subaddressIndex == other.subaddressIndex &&
          pending == other.pending;
}

/// A progress report from a running sync. Flat rather than an enum with
/// data, which keeps the Dart side free of code generation.
class SyncEvent {
  final SyncPhase phase;

  /// Blocks scanned so far.
  final BigInt scanned;

  /// Blocks the node (or the server's node) has.
  final BigInt tip;

  /// The node or server being used, while connecting.
  final String? node;
  final SyncFailure? failure;

  /// LWS only: outputs the server reported that are not this wallet's
  /// and were ignored.
  final int rejectedOutputs;

  /// LWS only: the server is still importing history from before the
  /// wallet was registered.
  final bool importPending;

  const SyncEvent({
    required this.phase,
    required this.scanned,
    required this.tip,
    this.node,
    this.failure,
    required this.rejectedOutputs,
    required this.importPending,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      scanned.hashCode ^
      tip.hashCode ^
      node.hashCode ^
      failure.hashCode ^
      rejectedOutputs.hashCode ^
      importPending.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncEvent &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          scanned == other.scanned &&
          tip == other.tip &&
          node == other.node &&
          failure == other.failure &&
          rejectedOutputs == other.rejectedOutputs &&
          importPending == other.importPending;
}

/// Why sync stopped with an error.
enum SyncFailure {
  /// The node or server could not be reached or misbehaved; it retries on
  /// its own.
  nodeUnreachable,

  /// The selected node or server serves another network.
  wrongNetwork,

  /// The selected node address is invalid.
  badNode,

  /// An LWS-mode wallet, but no light wallet server is set for its
  /// network.
  lwsServerNotSet,

  /// The owner has not yet agreed to share the view key with the server.
  lwsConsentNeeded,

  /// The server refused this wallet.
  lwsDenied,

  /// The server does not accept new wallets.
  lwsCreationRefused,
}

enum SyncPhase { connecting, scanning, synced, failed, stopped }

class WalletBalance {
  /// Atomic units (1 XMR = 10^12).
  final BigInt total;
  final BigInt unlocked;

  /// Incoming payments waiting in the transaction pool; not in `total`.
  final BigInt incoming;

  const WalletBalance({
    required this.total,
    required this.unlocked,
    required this.incoming,
  });

  @override
  int get hashCode => total.hashCode ^ unlocked.hashCode ^ incoming.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletBalance &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          unlocked == other.unlocked &&
          incoming == other.incoming;
}
