// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'network.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'sync.dart';

// These functions are ignored because they are not marked as `pub`: `address_row`, `create`, `new`, `set_label`, `store`, `with`, `with`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Inner`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `drop`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`

/// Opens the wallet directory. Call once at startup with the app's private
/// data directory.
///
/// # Errors
///
/// Fails if the directory cannot be created.
Future<void> initWalletStore({required String dir}) =>
    RustLib.instance.api.crateApiWalletsInitWalletStore(dir: dir);

/// Lists every wallet, on every network, in creation order.
///
/// # Errors
///
/// Fails if the wallet list cannot be read.
Future<List<WalletSummary>> listWallets() =>
    RustLib.instance.api.crateApiWalletsListWallets();

/// Generates a new seed. Nothing is stored until [`create_wallet_from_seed`].
Future<NewSeed> generateSeed({required SeedFormat format}) =>
    RustLib.instance.api.crateApiWalletsGenerateSeed(format: format);

/// Checks a seed without storing anything, so the restore form can say what
/// is wrong before asking for a name and password.
///
/// # Errors
///
/// Returns the reason the seed is invalid.
Future<SeedFormat> checkSeed({required String words}) =>
    RustLib.instance.api.crateApiWalletsCheckSeed(words: words);

/// Creates or restores a wallet from a 25-word or 16-word seed.
///
/// # Errors
///
/// Fails for an invalid seed, empty name, or storage error.
Future<OpenWallet> createWalletFromSeed({
  required String name,
  required Network network,
  required SyncMode mode,
  required String words,
  required String password,
  BigInt? restoreHeight,
}) => RustLib.instance.api.crateApiWalletsCreateWalletFromSeed(
  name: name,
  network: network,
  mode: mode,
  words: words,
  password: password,
  restoreHeight: restoreHeight,
);

/// Restores a wallet from its private spend key.
///
/// # Errors
///
/// Fails for an invalid key, empty name, or storage error.
Future<OpenWallet> createWalletFromSpendKey({
  required String name,
  required Network network,
  required SyncMode mode,
  required String spendKey,
  required String password,
  BigInt? restoreHeight,
}) => RustLib.instance.api.crateApiWalletsCreateWalletFromSpendKey(
  name: name,
  network: network,
  mode: mode,
  spendKey: spendKey,
  password: password,
  restoreHeight: restoreHeight,
);

/// Adds a view-only wallet from a standard address and private view key.
///
/// # Errors
///
/// Fails for a bad address, mismatched view key, empty name, or storage
/// error.
Future<OpenWallet> createViewOnlyWallet({
  required String name,
  required Network network,
  required SyncMode mode,
  required String address,
  required String viewKey,
  required String password,
  BigInt? restoreHeight,
}) => RustLib.instance.api.crateApiWalletsCreateViewOnlyWallet(
  name: name,
  network: network,
  mode: mode,
  address: address,
  viewKey: viewKey,
  password: password,
  restoreHeight: restoreHeight,
);

/// Unlocks a wallet with its password.
///
/// # Errors
///
/// [`WalletError::WrongPassword`] for a wrong password or a damaged file.
Future<OpenWallet> unlockWallet({
  required String id,
  required String password,
}) => RustLib.instance.api.crateApiWalletsUnlockWallet(
  id: id,
  password: password,
);

/// Renames a wallet. Works while locked.
///
/// # Errors
///
/// Fails for an empty name or unknown wallet.
Future<void> renameWallet({required String id, required String name}) =>
    RustLib.instance.api.crateApiWalletsRenameWallet(id: id, name: name);

/// Deletes a wallet after checking its password.
///
/// # Errors
///
/// [`WalletError::WrongPassword`] if the password does not open it.
Future<void> deleteWallet({required String id, required String password}) =>
    RustLib.instance.api.crateApiWalletsDeleteWallet(
      id: id,
      password: password,
    );

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<OpenWallet>>
abstract class OpenWallet implements RustOpaqueInterface {
  /// The primary address followed by every subaddress handed out so far
  /// in account 0, with labels.
  ///
  /// # Errors
  ///
  /// Fails if the wallet has been locked.
  List<AddressRow> addresses();

  /// Balance from what has been scanned so far.
  WalletBalance balance();

  /// Re-encrypts the wallet under a new password.
  ///
  /// # Errors
  ///
  /// [`WalletError::WrongPassword`] if `current` is wrong.
  Future<void> changePassword({
    required String current,
    required String newPassword,
  });

  /// Transactions found so far, newest first.
  List<HistoryItem> history();

  /// Wipes the keys now instead of waiting for Dart to release the object.
  void lock();

  /// Hands out the next subaddress in account 0 and saves the wallet.
  ///
  /// # Errors
  ///
  /// Fails if the wallet has been locked or cannot be saved.
  Future<AddressRow> newAddress({required String label});

  /// Returns the seed words after re-checking the password. `None` for
  /// wallets restored from keys or view-only wallets, which have no seed.
  ///
  /// # Errors
  ///
  /// [`WalletError::WrongPassword`] if the password does not open the file.
  Future<List<String>?> revealSeed({required String password});

  /// Sets or clears (empty string) an address label and saves the wallet.
  ///
  /// # Errors
  ///
  /// Fails if the wallet has been locked or cannot be saved.
  Future<void> setAddressLabel({
    required int account,
    required int index,
    required String label,
  });

  /// Starts syncing in the background and reports through `sink`. Keeps
  /// following new blocks until [`OpenWallet::stop_sync`] or
  /// [`OpenWallet::lock`]. Calling it while sync runs does nothing.
  Stream<SyncEvent> startSync();

  /// Stops background sync after the current batch.
  void stopSync();

  /// The wallet's registry entry.
  ///
  /// # Errors
  ///
  /// Fails if the wallet has been locked.
  WalletSummary summary();
}

/// One receiving address of an unlocked wallet.
class AddressRow {
  final int account;
  final int index;
  final String address;
  final String label;

  const AddressRow({
    required this.account,
    required this.index,
    required this.address,
    required this.label,
  });

  @override
  int get hashCode =>
      account.hashCode ^ index.hashCode ^ address.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddressRow &&
          runtimeType == other.runtimeType &&
          account == other.account &&
          index == other.index &&
          address == other.address &&
          label == other.label;
}

/// A freshly generated seed, shown once so the user can write it down.
class NewSeed {
  final SeedFormat format;
  final List<String> words;

  const NewSeed({required this.format, required this.words});

  @override
  int get hashCode => format.hashCode ^ words.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NewSeed &&
          runtimeType == other.runtimeType &&
          format == other.format &&
          words == other.words;
}

enum SeedFormat {
  /// 16 words; also records when the wallet was created.
  polyseed,

  /// Monero's original 25 words.
  classic,
}

enum SyncMode { full, lws }

/// Why a wallet operation failed. The app maps each case to its own message.
enum WalletError {
  wrongPassword,
  wrongWordCount,
  unknownWord,
  badChecksum,
  unsupportedPolyseed,
  malformedKey,
  invalidKey,
  badAddress,
  viewKeyMismatch,
  notStandardAddress,
  emptyName,
  damaged,
  newerVersion,
  notFound,
  storage,
  notInitialized,
}

/// A wallet as shown in the list. Nothing here is secret.
class WalletSummary {
  final String id;
  final String name;
  final Network network;
  final SyncMode mode;
  final bool viewOnly;
  final BigInt createdAt;

  const WalletSummary({
    required this.id,
    required this.name,
    required this.network,
    required this.mode,
    required this.viewOnly,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      network.hashCode ^
      mode.hashCode ^
      viewOnly.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          network == other.network &&
          mode == other.mode &&
          viewOnly == other.viewOnly &&
          createdAt == other.createdAt;
}
