// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'book.dart';
import 'coins.dart';
import 'cold.dart';
import 'network.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'requests.dart';
import 'send.dart';
import 'sync.dart';

// These functions are ignored because they are not marked as `pub`: `address_row`, `create`, `new`, `set_label`, `store`, `with`, `with`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Inner`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `drop`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`

/// Opens the wallet directory. Call once at startup with the app's private
/// data directory.
///
/// # Errors
///
/// Fails if the directory cannot be created.
Future<void> initWalletStore({required String dir}) =>
    RustLib.instance.api.crateApiWalletsInitWalletStore(dir: dir);

/// Lists every wallet, on every network, in creation order.
///
/// # Errors
///
/// Fails if the wallet list cannot be read.
Future<List<WalletSummary>> listWallets() =>
    RustLib.instance.api.crateApiWalletsListWallets();

/// Generates a new seed. Nothing is stored until [`create_wallet_from_seed`].
Future<NewSeed> generateSeed({required SeedFormat format}) =>
    RustLib.instance.api.crateApiWalletsGenerateSeed(format: format);

/// Checks a seed without storing anything, so the restore form can say what
/// is wrong before asking for a name and password.
///
/// # Errors
///
/// Returns the reason the seed is invalid.
Future<SeedFormat> checkSeed({required String words}) =>
    RustLib.instance.api.crateApiWalletsCheckSeed(words: words);

/// Creates or restores a wallet from a 25-word or 16-word seed.
/// `created_here` is true for a seed generated just now, which has no
/// earlier history.
///
/// # Errors
///
/// Fails for an invalid seed, empty name, or storage error.
Future<OpenWallet> createWalletFromSeed({
  required String name,
  required Network network,
  required SyncMode mode,
  required String words,
  required String password,
  BigInt? restoreHeight,
  required bool createdHere,
}) => RustLib.instance.api.crateApiWalletsCreateWalletFromSeed(
  name: name,
  network: network,
  mode: mode,
  words: words,
  password: password,
  restoreHeight: restoreHeight,
  createdHere: createdHere,
);

/// Restores a wallet from its private spend key.
///
/// # Errors
///
/// Fails for an invalid key, empty name, or storage error.
Future<OpenWallet> createWalletFromSpendKey({
  required String name,
  required Network network,
  required SyncMode mode,
  required String spendKey,
  required String password,
  BigInt? restoreHeight,
}) => RustLib.instance.api.crateApiWalletsCreateWalletFromSpendKey(
  name: name,
  network: network,
  mode: mode,
  spendKey: spendKey,
  password: password,
  restoreHeight: restoreHeight,
);

/// Adds a view-only wallet from a standard address and private view key.
///
/// # Errors
///
/// Fails for a bad address, mismatched view key, empty name, or storage
/// error.
Future<OpenWallet> createViewOnlyWallet({
  required String name,
  required Network network,
  required SyncMode mode,
  required String address,
  required String viewKey,
  required String password,
  BigInt? restoreHeight,
}) => RustLib.instance.api.crateApiWalletsCreateViewOnlyWallet(
  name: name,
  network: network,
  mode: mode,
  address: address,
  viewKey: viewKey,
  password: password,
  restoreHeight: restoreHeight,
);

/// Unlocks a wallet with its password.
///
/// # Errors
///
/// [`WalletError::WrongPassword`] for a wrong password or a damaged file.
Future<OpenWallet> unlockWallet({
  required String id,
  required String password,
}) => RustLib.instance.api.crateApiWalletsUnlockWallet(
  id: id,
  password: password,
);

/// Renames a wallet. Works while locked.
///
/// # Errors
///
/// Fails for an empty name or unknown wallet.
Future<void> renameWallet({required String id, required String name}) =>
    RustLib.instance.api.crateApiWalletsRenameWallet(id: id, name: name);

/// Deletes a wallet after checking its password.
///
/// # Errors
///
/// [`WalletError::WrongPassword`] if the password does not open it.
Future<void> deleteWallet({required String id, required String password}) =>
    RustLib.instance.api.crateApiWalletsDeleteWallet(
      id: id,
      password: password,
    );

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<OpenWallet>>
abstract class OpenWallet implements RustOpaqueInterface {
  /// The primary address followed by every subaddress handed out so far
  /// in account 0, with labels.
  ///
  /// # Errors
  ///
  /// Fails if the wallet has been locked.
  List<AddressRow> addresses();

  /// Cold wallet: answers a request. Signing asks for the password again.
  ///
  /// # Errors
  ///
  /// [`ColdFailure::WrongPassword`] leaves the request usable; a request
  /// can be signed once.
  Future<ColdMessage> answerColdRequest({
    required ColdRequest request,
    required String password,
  });

  /// Balance from what has been scanned so far.
  WalletBalance balance();

  /// Re-encrypts the wallet under a new password.
  ///
  /// # Errors
  ///
  /// [`WalletError::WrongPassword`] if `current` is wrong.
  Future<void> changePassword({
    required String current,
    required String newPassword,
  });

  /// Unspent coins, largest first.
  ///
  /// # Errors
  ///
  /// Fails if the wallet has been locked.
  List<CoinRow> coins();

  /// Watching wallet: how many coins still need key images from the cold
  /// wallet before they can be spent.
  ///
  /// # Errors
  ///
  /// Fails if the wallet has been locked.
  int coinsWithoutKeyImages();

  /// The pairing code a watching wallet is created from. It carries the
  /// private view key, so it asks for the password.
  ///
  /// # Errors
  ///
  /// [`ColdFailure::WrongPassword`], or [`ColdFailure::ViewOnly`].
  Future<ColdMessage> coldPairing({required String password});

  /// Watching wallet: asks the cold wallet for the key images of every
  /// coin that lacks one, so spends become visible.
  ///
  /// # Errors
  ///
  /// [`ColdFailure::NotWatching`] for a wallet that can sign itself.
  Future<ColdMessage> coldSyncRequest();

  /// Checks `password` and publishes `send`. Its inputs count as spent at
  /// once; sync confirms the spend when it is mined. Sync is paused while
  /// publishing; start it again afterwards.
  ///
  /// # Errors
  ///
  /// [`SendError::WrongPassword`] leaves `send` usable; after any other
  /// error it is discarded.
  Future<void> confirmSend({
    required PreparedSend send,
    required String password,
  });

  /// Saved recipients, by name.
  ///
  /// # Errors
  ///
  /// Fails if the wallet has been locked.
  List<ContactRow> contacts();

  /// Creates a request for `amount` (atomic units) on a new subaddress
  /// labelled `label`, optionally expiring after `expires_in_hours`.
  ///
  /// # Errors
  ///
  /// Fails for a zero amount ([`WalletError::Storage`] is not used for
  /// that: [`WalletError::EmptyName`] stands for "nothing asked"), or if
  /// the wallet cannot be saved.
  Future<RequestRow> createRequest({
    required BigInt amount,
    required String label,
    int? expiresInHours,
  });

  /// Removes the recipient with `address`.
  ///
  /// # Errors
  ///
  /// Fails if the wallet has been locked or cannot be saved.
  Future<void> deleteContact({required String address});

  /// Removes a request. Its subaddress stays, with its label.
  ///
  /// # Errors
  ///
  /// Fails if the wallet has been locked or cannot be saved.
  Future<void> deleteRequest({required String id});

  /// Records that the owner agreed to share this wallet's private view
  /// key with `server`, and saves the wallet.
  ///
  /// # Errors
  ///
  /// Fails if the wallet has been locked or cannot be saved.
  Future<void> grantLwsConsent({required String server});

  /// Transactions found so far, newest first.
  List<HistoryItem> history();

  /// Watching wallet: takes the cold wallet's answer, with the
  /// destinations of the [`ColdSend`] it answers (empty for a sync). Key
  /// images are
  /// learned (and the chain rescanned from the oldest affected coin in
  /// full mode); a signed transaction is checked to spend only this
  /// wallet's coins and published. Sync is paused; start it again
  /// afterwards.
  ///
  /// # Errors
  ///
  /// See [`ColdFailure`]; publishing failures are [`ColdFailure::Send`].
  Future<ColdImport> importColdAnswer({
    required List<int> message,
    required List<Payment> destinations,
  });

  /// Whether this is an offline (cold) wallet.
  ///
  /// # Errors
  ///
  /// Fails if the wallet has been locked.
  bool isCold();

  /// Wipes the keys now instead of waiting for Dart to release the object.
  void lock();

  /// The light wallet server this LWS-mode wallet would sync from, if the
  /// owner has not yet agreed to share the view key with it. `None` when
  /// consent is already given, no server is set, or the wallet uses full
  /// sync.
  ///
  /// # Errors
  ///
  /// Fails if the wallet has been locked.
  Future<String?> lwsConsentNeeded();

  /// Hands out the next subaddress in account 0 and saves the wallet.
  ///
  /// # Errors
  ///
  /// Fails if the wallet has been locked or cannot be saved.
  Future<AddressRow> newAddress({required String label});

  /// Watching wallet: builds a transaction for the cold wallet to sign.
  ///
  /// # Errors
  ///
  /// [`ColdFailure::Send`] with the reason in the returned summary's
  /// absence; call [`OpenWallet::prepare_send`]'s error mapping in the app.
  Future<ColdSend> prepareColdSend({
    required List<Payment> payments,
    String? sweepTo,
    required FeePriority priority,
  });

  /// Builds and signs a transaction paying `payments`, or, with
  /// `sweep_to`, sending everything spendable to that address. Nothing is
  /// published; show [`PreparedSend::summary`] and call
  /// [`OpenWallet::confirm_send`].
  ///
  /// # Errors
  ///
  /// See [`SendError`]; sync must have reached the chain tip first.
  Future<PreparedSend> prepareSend({
    required List<Payment> payments,
    String? sweepTo,
    required FeePriority priority,
  });

  /// [`OpenWallet::prepare_send`], spending only the coins with these
  /// one-time keys (hex), as listed by [`OpenWallet::coins`].
  ///
  /// # Errors
  ///
  /// As [`OpenWallet::prepare_send`]; [`SendError::InsufficientFunds`] if
  /// the chosen coins do not cover the amount and fee.
  Future<PreparedSend> prepareSendFromCoins({
    required List<Payment> payments,
    String? sweepTo,
    required FeePriority priority,
    required List<String> coins,
  });

  /// Cold wallet: reads and checks a scanned request. Nothing is signed
  /// until [`OpenWallet::answer_cold_request`].
  ///
  /// # Errors
  ///
  /// See [`ColdFailure`]: a transaction that is not this wallet's own and
  /// sane is refused here.
  Future<ColdRequest> readColdRequest({required List<int> message});

  /// Requests, newest first, with what each has received.
  ///
  /// # Errors
  ///
  /// Fails if the wallet has been locked.
  List<RequestRow> requests();

  /// Returns the seed words after re-checking the password. `None` for
  /// wallets restored from keys or view-only wallets, which have no seed.
  ///
  /// # Errors
  ///
  /// [`WalletError::WrongPassword`] if the password does not open the file.
  Future<List<String>?> revealSeed({required String password});

  /// The transaction key of a transaction this wallet sent, after
  /// checking the password. With it and the recipient's address, anyone
  /// can verify the payment (for example with `check_tx_key`).
  ///
  /// # Errors
  ///
  /// [`WalletError::WrongPassword`], or [`WalletError::NotFound`] if no key
  /// is stored for `tx_hash`.
  Future<String> revealTxKey({
    required String txHash,
    required String password,
  });

  /// Saves a recipient, replacing any entry with the same address.
  ///
  /// # Errors
  ///
  /// [`WalletError::EmptyName`], or [`WalletError::BadAddress`] for an
  /// address not on this wallet's network.
  Future<void> saveContact({required String name, required String address});

  /// Sets or clears (empty string) an address label and saves the wallet.
  ///
  /// # Errors
  ///
  /// Fails if the wallet has been locked or cannot be saved.
  Future<void> setAddressLabel({
    required int account,
    required int index,
    required String label,
  });

  /// Freezes or thaws the coin with one-time key `key` (hex).
  ///
  /// # Errors
  ///
  /// Fails if the wallet has been locked or cannot be saved.
  Future<void> setCoinFrozen({required String key, required bool frozen});

  /// Makes this an offline wallet that only signs for a watching wallet,
  /// or a normal wallet again. Stops sync and forgets what was scanned.
  ///
  /// # Errors
  ///
  /// [`ColdFailure::ViewOnly`] for a view-only wallet, which cannot sign.
  Future<void> setCold({required bool cold});

  /// Switches between full sync and a light wallet server. Stops sync and
  /// clears what was scanned; start sync again afterwards.
  ///
  /// # Errors
  ///
  /// Fails if the wallet has been locked or cannot be saved.
  Future<void> setSyncMode({required SyncMode mode});

  /// Sets the note for `tx_hash`; an empty note removes it.
  ///
  /// # Errors
  ///
  /// Fails if the wallet has been locked or cannot be saved.
  Future<void> setTxNote({required String txHash, required String note});

  /// Starts syncing in the background and reports through `sink`. Keeps
  /// following new blocks until [`OpenWallet::stop_sync`] or
  /// [`OpenWallet::lock`]. Calling it again restarts sync.
  Stream<SyncEvent> startSync();

  /// Stops background sync after the current step.
  void stopSync();

  /// The wallet's registry entry.
  ///
  /// # Errors
  ///
  /// Fails if the wallet has been locked.
  WalletSummary summary();

  /// Notes and sending details for `tx_hash` (hex).
  ///
  /// # Errors
  ///
  /// Fails if the wallet has been locked.
  TxDetails txDetails({required String txHash});
}

/// One receiving address of an unlocked wallet.
class AddressRow {
  final int account;
  final int index;
  final String address;
  final String label;

  const AddressRow({
    required this.account,
    required this.index,
    required this.address,
    required this.label,
  });

  @override
  int get hashCode =>
      account.hashCode ^ index.hashCode ^ address.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddressRow &&
          runtimeType == other.runtimeType &&
          account == other.account &&
          index == other.index &&
          address == other.address &&
          label == other.label;
}

/// A freshly generated seed, shown once so the user can write it down.
class NewSeed {
  final SeedFormat format;
  final List<String> words;

  const NewSeed({required this.format, required this.words});

  @override
  int get hashCode => format.hashCode ^ words.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NewSeed &&
          runtimeType == other.runtimeType &&
          format == other.format &&
          words == other.words;
}

enum SeedFormat {
  /// 16 words; also records when the wallet was created.
  polyseed,

  /// Monero's original 25 words.
  classic,
}

enum SyncMode { full, lws }

/// Why a wallet operation failed. The app maps each case to its own message.
enum WalletError {
  wrongPassword,
  wrongWordCount,
  unknownWord,
  badChecksum,
  unsupportedPolyseed,
  malformedKey,
  invalidKey,
  badAddress,
  viewKeyMismatch,
  notStandardAddress,
  emptyName,
  damaged,
  newerVersion,
  notFound,
  storage,
  notInitialized,
}

/// A wallet as shown in the list. Nothing here is secret.
class WalletSummary {
  final String id;
  final String name;
  final Network network;
  final SyncMode mode;
  final bool viewOnly;
  final BigInt createdAt;

  /// An offline wallet that only signs for a watching wallet.
  final bool cold;

  const WalletSummary({
    required this.id,
    required this.name,
    required this.network,
    required this.mode,
    required this.viewOnly,
    required this.createdAt,
    required this.cold,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      network.hashCode ^
      mode.hashCode ^
      viewOnly.hashCode ^
      createdAt.hashCode ^
      cold.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          network == other.network &&
          mode == other.mode &&
          viewOnly == other.viewOnly &&
          createdAt == other.createdAt &&
          cold == other.cold;
}
